// <auto-generated />
namespace VirtoCommerce.SitemapsModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AcceptedStaticContentFilenameExtensions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AcceptedStaticContentFilenameExtensions));
        
        string IMigrationMetadata.Id
        {
            get { return "201707240958160_AcceptedStaticContentFilenameExtensions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
